version: '3.7'
networks:
  supa-network:
    driver: bridge
services:
  backend:
    build: ./backend
    container_name: supa-backend
    image: supa-backend:1.0
    ports:
      - "5000:5000"
    environment:
      BACKEND_HOST: '0.0.0.0'
      BACKEND_PORT: 5000
      GRAPH_DATABASE_URI: 'bolt://neo4j-prd:7687'
      GRAPH_DATABASE_PASSWORD: 'password'
      SQL_DATABASE_URI: 'mysql://user:password@mysql-prd:3306/supa'
      INGESTED: "true"
    depends_on:
      - mysql-prd
      - neo4j-prd
    restart: on-failure
    networks:
      - supa-network
    volumes:
      - ./backend:/backend
  mysql-prd:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'supa'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supa-network
    volumes:
      - ingestion-volume:/var/lib/mysql
  neo4j-prd:
    image: neo4j:4.0.8
    environment:
      NEO4J_AUTH: 'neo4j/password'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supa-network

volumes:
  ingestion-volume:
  neo4j-data:
