version: '3.7'
networks:
  supa-network:
    driver: bridge
services:
  backend:
    build: ./backend
    container_name: supa-backend
    image: supa-backend:1.0
    ports:
      - "5000:5000"
    environment:
      BACKEND_HOST: '0.0.0.0'
      BACKEND_PORT: 5000
      GRAPH_DATABASE_URI: 'bolt://neo4j-test:7687'
      GRAPH_DATABASE_PASSWORD: 'password'
      SQL_DATABASE_URI: 'mysql://user:password@mysql-test:3306/supa'
      INGESTED: "false"
    depends_on:
      - mysql-test
      - neo4j-test
    restart: on-failure
    networks:
      - supa-network
    volumes:
      - ./backend:/backend
  ingestion:
    build: ./ingestion
    container_name: supa-ingestion
    image: supa-ingestion:1.0
    ports:
      - "6000:6000"
    environment:
      BACKEND_HOST: 'http://backend:5000'
      INIT_SQL: "true"
      INIT_GRAPH: "true"
      GUIDELINES_CSV_FILE: "Guidelines_Criteria.csv"
      POSTAL_CODE_JSON_FILE: "Postal_Code.json"
      HDB_COMMERCIAL_JSON_FILE: "HDB_Commercial.json"
      SHOPHOUSE_JSON_FILE: "Shophouse.json"
      LAND_USE_JSON_FILE: "Land_Use.json"
      SHOPHOUSE_GUIDELINES_JSON_FILE: "Shophouse_Guidelines.json"
      PROBLEMATIC_AREA_JSON_FILE: "Problematic_Area.json"
      CASES_DATA_DIRECTORY: "./sample/"
    networks:
      - supa-network
    command: ["./wait-for-it.sh", "backend:5000", "--", "python", "run.py"]
  mysql-test:
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'supa'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supa-network
    volumes:
      - ingestion-volume:/var/lib/mysql
  neo4j-test:
    image: neo4j:4.0.8
    environment:
      NEO4J_AUTH: 'neo4j/password'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supa-network

volumes:
  ingestion-volume:
  neo4j-data:
