generic_land_use_types = [
    "BUSINESS",
    "COMMERCIAL_GEN",
    "RESIDENTIAL_GEN",
    "MIXED_DEVELOPMENT",
    "SPECIALISED_USE"
]

specific_land_use_type_map = {
    "RESIDENTIAL": "RESIDENTIAL_GEN",
    "RESIDENTIAL WITH COMMERCIAL AT 1ST STOREY": "MIXED_DEVELOPMENT",
    "ResComm": "MIXED_DEVELOPMENT",
    "RESIDENTIAL / INSTITUTION": "RESIDENTIAL_GEN",
    "COMMERCIAL": "COMMERCIAL_GEN",
    "COMMERCIAL / INSTITUTION": "COMMERCIAL_GEN",
    "HOTEL": "SPECIALISED_USE",
    "WHITE": "MIXED_DEVELOPMENT",
    "BUSINESS PARK": "BUSINESS",
    "BUSINESS PARK - WHITE": "BUSINESS",
    "BUSINESS 1": "BUSINESS",
    "BUSINESS 2": "BUSINESS",
    "BUSINESS 1 - WHITE": "BUSINESS",
    "BUSINESS 2 - WHITE": "BUSINESS",
    "HEALTH & MEDICAL CARE": "SPECIALISED_USE",
    "EDUCATIONAL INSTITUTION": "SPECIALISED_USE",
    "PLACE OF WORSHIP": "SPECIALISED_USE",
    "CIVIC & COMMUNITY INSTITUTION": "SPECIALISED_USE",
}