generic_use_classes = [
    "FoodBev",
    "ShopOfficeSvc",
    "Education",
    "SportsRec",
    "Accommodation",
    "IndRelatedUse",
    "CommunityRelatedUse",
    "ReligiousUse"
]

specific_use_class_map = {
    "Restaurant": "FoodBev",
    "Bar/Pub": "FoodBev",
    "Restaurant and Bar": "FoodBev",
    "Nightclub": "FoodBev",
    "Shop": "ShopOfficeSvc",
    "Laundromat": "ShopOfficeSvc",
    "Office": "ShopOfficeSvc",
    "Massage Establishment": "ShopOfficeSvc",
    "Medical Clinic": "ShopOfficeSvc",
    "Pet Shop": "ShopOfficeSvc",
    "Pet Boarding": "ShopOfficeSvc",
    "Commercial School": "Education",
    "Childcare Centre": "Education",
    "Fitness Centre": "SportsRec",
    "Amusement Centre": "SportsRec",
    "Residential": "Accommodation",
    "Backpacker Hostel": "Accommodation",
    "Hotel": "Accommodation",
    "Student Hostel": "Accommodation",
    "Service Apartment": "Accommodation",
    "Worker Dorm": "Accommodation",
    "Light Industrial Use": "IndRelatedUse",
    "General Industrial Use": "IndRelatedUse",
    "Industrial Training": "IndRelatedUse",
    "Warehouse": "IndRelatedUse",
    "Industrial Canteen": "IndRelatedUse",
    "Showroom": "IndRelatedUse",
    "E-Business": "IndRelatedUse",
    "Core Media Activities": "IndRelatedUse",
    "Association/Community Club/Family Service Centre": "CommunityRelatedUse",
    "Religious Activities": "ReligiousUse",
    "Limited & Non-Exclusive Religious Use": "ReligiousUse",
}
