generic_use_classes = [
    "FoodBev",
    "ShopOfficeSvc",
    "Education",
    "SportsRec",
    "Accommodation",
    "IndRelatedUse",
    "CommunityRelatedUse",
    "ReligiousUse"
]

specific_use_class_map = {
    "Restaurant": "FoodBev",
    "BarPub": "FoodBev",
    "RestaurantBar": "FoodBev",
    "Nightclub": "FoodBev",
    "Shop": "ShopOfficeSvc",
    "Laundromat": "ShopOfficeSvc",
    "Office": "ShopOfficeSvc",
    "MassageEstablishment": "ShopOfficeSvc",
    "MedicalClinic": "ShopOfficeSvc",
    "PetShop": "ShopOfficeSvc",
    "PetBoarding": "ShopOfficeSvc",
    "CommercialSchool": "Education",
    "Childcare": "Education",
    "FitnessCentre": "SportsRec",
    "AmusementCentre": "SportsRec",
    "Residential": "Accommodation",
    "BackpackerHostel": "Accommodation",
    "Hotel": "Accommodation",
    "StudentHostel": "Accommodation",
    "ServiceApartment": "Accommodation",
    "WorkerDorm": "Accommodation",
    "LightIndUse": "IndRelatedUse",
    "GeneralIndUse": "IndRelatedUse",
    "IndTraining": "IndRelatedUse",
    "Warehouse": "IndRelatedUse",
    "IndCanteen": "IndRelatedUse",
    "Showroom": "IndRelatedUse",
    "EBusiness": "IndRelatedUse",
    "CoreMediaActivities": "IndRelatedUse",
    "CommunityClub": "CommunityRelatedUse",
    "ReligiousActivities": "ReligiousUse",
    "LimitedReligiousUse": "ReligiousUse",
}
